name: Auto versioning

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate-auto-versioning:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache-dir-path.outputs.cache-hit != 'true'
        run: yarn

      - name: Auto versioning
        run: yarn bump:packages

      - name: Commit versioning
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: updated versions"
