name: auto-versioning

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate-auto-versioning:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Auto versioning
        run: yarn bump:packages

      - name: Commit versioning
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: updated versions"
